require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/unicorn/production.rb'
    - 'config/deploy.rb'
    - 'config/unicorn.conf.rb'
    - 'notifications_controller.rb'
    - 'users_controller.rb:'
    - 'spec_helper.rb'
    - 'capybara.rb'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Style/SpaceAroundOperators:
  Severity: warning
  AllowForAlignment: true
