version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /anicheck/config/unicorn.conf.rb
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/anicheck:cached
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/anicheck/tmp/sockets
      #画像データとかをnginxと共有
      - public-data:/anicheck/public

  db:
    image: mysql:5.7
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: anicheck_development
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
    #dbのデータを永続化しておく
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/anicheck/tmp/sockets
      - public-data:/anicheck/public
    depends_on:
      - web

volumes:
  public-data:
  tmp-data:
  mysql-data:
