development:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#  secret_key_base: 09870883645626cac8619de406615b7881848b79fc1479ea9534f01900e7e64cbb705d75d8d1009b931de3bc6a93374d78194cbb7999474f4249b89717ac3f6f
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
